// File Actions
export const ADD_FILE_REQUEST = 'ADD_FILE_REQUEST';
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const ADD_FILE_FAILURE = 'ADD_FILE_FAILURE';

export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';

export const UPDATE_FILE_REQUEST = 'UPDATE_FILE_REQUEST';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_FAILURE = 'UPDATE_FILE_FAILURE';

export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';

export const FETCH_FILES_METADATA_REQUEST = 'FETCH_FILES_METADATA_REQUEST';
export const FETCH_FILES_METADATA_SUCCESS = 'FETCH_FILES_METADATA_SUCCESS';
export const FETCH_FILES_METADATA_FAILURE = 'FETCH_FILES_METADATA_FAILURE';

export const FETCH_ALL_FILES_METADATA_REQUEST = 'FETCH_ALL_FILES_METADATA_REQUEST';
export const FETCH_ALL_FILES_METADATA_SUCCESS = 'FETCH_ALL_FILES_METADATA_SUCCESS';
export const FETCH_ALL_FILES_METADATA_FAILURE = 'FETCH_ALL_FILES_METADATA_FAILURE';

export const FETCH_FILE_DATA_REQUEST = "FETCH_FILE_DATA_REQUEST";
export const FETCH_FILE_DATA_SUCCESS = "FETCH_FILE_DATA_SUCCESS";
export const FETCH_FILE_DATA_FAILURE = "FETCH_FILE_DATA_FAILURE";

export const UPDATE_FILE_CONTENT_REQUEST = "UPDATE_FILE_CONTENT_REQUEST";
export const UPDATE_FILE_CONTENT_SUCCESS = "UPDATE_FILE_CONTENT_SUCCESS";
export const UPDATE_FILE_CONTENT_FAILURE = "UPDATE_FILE_CONTENT_FAILURE";

// Folder Actions
export const ADD_FOLDER_REQUEST = 'ADD_FOLDER_REQUEST';
export const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS';
export const ADD_FOLDER_FAILURE = 'ADD_FOLDER_FAILURE';

export const UPDATE_FOLDER_REQUEST = 'UPDATE_FOLDER_REQUEST';
export const UPDATE_FOLDER_SUCCESS = 'UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_FAILURE = 'UPDATE_FOLDER_FAILURE';

export const DELETE_FOLDER_REQUEST = 'DELETE_FOLDER_REQUEST';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAILURE = 'DELETE_FOLDER_FAILURE';

export const FETCH_FOLDERS_REQUEST = 'FETCH_FOLDERS_REQUEST';
export const FETCH_FOLDERS_SUCCESS = 'FETCH_FOLDERS_SUCCESS';
export const FETCH_FOLDERS_FAILURE = 'FETCH_FOLDERS_FAILURE';


export const UPDATE_FOLDER_NAME_OPTIMISTIC = 'UPDATE_FOLDER_NAME_OPTIMISTIC';
export const REPLACE_TEMP_FOLDER_WITH_REEL_ONE_SUCCESS = 'REPLACE_TEMP_FOLDER_WITH_REEL_ONE_SUCCESS';
export const REMOVE_TEMP_FOLDER_AFTER_BACKEND_CREATION_FAILURE = 'REMOVE_TEMP_FOLDER_AFTER_BACKEND_CREATION_FAILURE';

// Action Types for File Operations (Upload/Download)
export const ADD_OPERATION = 'ADD_OPERATION';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_OPERATION = 'REMOVE_OPERATION';
export const OPERATION_COMPLETE = 'OPERATION_COMPLETE';
