// Signature Requests Action Types

// Fetch signature requests
export const FETCH_SIGNATURE_REQUESTS_REQUEST = 'FETCH_SIGNATURE_REQUESTS_REQUEST';
export const FETCH_SIGNATURE_REQUESTS_SUCCESS = 'FETCH_SIGNATURE_REQUESTS_SUCCESS';
export const FETCH_SIGNATURE_REQUESTS_FAILURE = 'FETCH_SIGNATURE_REQUESTS_FAILURE';

// View signature request document
export const VIEW_SIGNATURE_DOCUMENT_REQUEST = 'VIEW_SIGNATURE_DOCUMENT_REQUEST';
export const VIEW_SIGNATURE_DOCUMENT_SUCCESS = 'VIEW_SIGNATURE_DOCUMENT_SUCCESS';
export const VIEW_SIGNATURE_DOCUMENT_FAILURE = 'VIEW_SIGNATURE_DOCUMENT_FAILURE';

// Sign document
export const SIGN_DOCUMENT_REQUEST = 'SIGN_DOCUMENT_REQUEST';
export const SIGN_DOCUMENT_SUCCESS = 'SIGN_DOCUMENT_SUCCESS';
export const SIGN_DOCUMENT_FAILURE = 'SIGN_DOCUMENT_FAILURE';

// Decline signature request
export const DECLINE_SIGNATURE_REQUEST_REQUEST = 'DECLINE_SIGNATURE_REQUEST_REQUEST';
export const DECLINE_SIGNATURE_REQUEST_SUCCESS = 'DECLINE_SIGNATURE_REQUEST_SUCCESS';
export const DECLINE_SIGNATURE_REQUEST_FAILURE = 'DECLINE_SIGNATURE_REQUEST_FAILURE';

// Clear signature document data
export const CLEAR_SIGNATURE_DOCUMENT_DATA = 'CLEAR_SIGNATURE_DOCUMENT_DATA';
