// Like
export const LIKE_API_SUCCESS = "LIKE_API_SUCCESS";
export const LIKE_API_FAILURE = "LIKE_API_FAILURE";
export const LIKE_API_REQUEST = "LIKE_API_REQUEST";

// get Like
export const GET_LIKE_API_SUCCESS = "GET_LIKE_API_SUCCESS";
export const GET_LIKE_API_FAILURE = "GET_LIKE_API_FAILURE";
export const GET_LIKE_API_REQUEST = "GET_LIKE_API_REQUEST";

// Dislike
export const DISLIKE_API_SUCCESS = "DISLIKE__API_SUCCESS";
export const DISLIKE_API_FAILURE = "DISLIKE__API_FAILURE";
export const DISLIKE_API_REQUEST = "DISLIKE_API_REQUEST";

// get user Likes by entity name
export const GET_USER_LIKES_BY_ENTITY_NAME_API_REQUEST =
  "GET_USER_LIKES_BY_ENTITY_NAME_API_REQUEST";
export const GET_USER_LIKES_BY_ENTITY_NAME_API_SUCCESS =
  "GET_USER_LIKES_BY_ENTITY_NAME_API_SUCCESS";
export const GET_USER_LIKES_BY_ENTITY_NAME_API_FAILURE =
  "GET_USER_LIKES_BY_ENTITY_NAME_API_FAILURE";

// count_likes_by_entity_record
export const COUNT_LIKES_BY_ENTITY_RECORD_API_REQUEST =
  "COUNT_LIKES_BY_ENTITY_RECORD_API_REQUEST";
export const COUNT_LIKES_BY_ENTITY_RECORD_API_SUCCESS =
  "COUNT_LIKES_BY_ENTITY_RECORD_API_SUCCESS";
export const COUNT_LIKES_BY_ENTITY_RECORD_API_FAILURE =
  "COUNT_LIKES_BY_ENTITY_RECORD_API_FAILURE";

// get Comments
export const GET_COMMENTS_API_SUCCESS = "GET_COMMENTS_API_SUCCESS";
export const GET_COMMENTS_API_FAILURE = "GET_COMMENTS_API_FAILURE";
export const GET_COMMENTS_API_REQUEST = "GET_COMMENTS_API_REQUEST";

// get Comments By RecordId
export const GET_COMMENTS_RECORD_ID_API_SUCCESS =
  "GET_COMMENTS_RECORD_ID_API_SUCCESS";
export const GET_COMMENTS_RECORD_ID_API_FAILURE =
  "GET_COMMENTS_RECORD_ID_API_FAILURE";
export const GET_COMMENTS_RECORD_ID_API_REQUEST =
  "GET_COMMENTS_RECORD_ID_API_REQUEST";

// save Comments
export const SAVE_COMMENT_API_SUCCESS = "SAVE_COMMENT_API_SUCCESS";
export const SAVE_COMMENT_API_FAILURE = "SAVE_COMMENT_API_FAILURE";
export const SAVE_COMMENT_API_REQUEST = "SAVE_COMMENT_API_REQUEST";

// delete Comments
export const DELETE_COMMENT_API_SUCCESS = "DELETE_COMMENT_API_SUCCESS";
export const DELETE_COMMENT_API_FAILURE = "DELETE_COMMENT_API_FAILURE";
export const DELETE_COMMENT_API_REQUEST = "DELETE_COMMENT_API_REQUEST";

// Interaction Parameters
export const INTERACTION_PARAMETERS_API_SUCCESS =
  "INTERACTION_PARAMETERS_API_SUCCESS";
export const INTERACTION_PARAMETERS_API_FAILURE =
  "INTERACTION_PARAMETERS_API_FAILURE";
export const INTERACTION_PARAMETERS_API_REQUEST =
  "INTERACTION_PARAMETERS_API_REQUEST";

export const INTERACTION_API_LOADING = "SERVICES_API_LOADING";
