// Invoice action types
export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';

export const ADD_INVOICE_REQUEST = 'ADD_INVOICE_REQUEST';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAILURE = 'ADD_INVOICE_FAILURE';

export const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_FAILURE = 'UPDATE_INVOICE_FAILURE';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILURE = 'DELETE_INVOICE_FAILURE';

export const GENERATE_INVOICE_PDF_REQUEST = 'GENERATE_INVOICE_PDF_REQUEST';
export const GENERATE_INVOICE_PDF_SUCCESS = 'GENERATE_INVOICE_PDF_SUCCESS';
export const GENERATE_INVOICE_PDF_FAILURE = 'GENERATE_INVOICE_PDF_FAILURE';

export const SAVE_INVOICE_TO_APP_REQUEST = 'SAVE_INVOICE_TO_APP_REQUEST';
export const SAVE_INVOICE_TO_APP_SUCCESS = 'SAVE_INVOICE_TO_APP_SUCCESS';
export const SAVE_INVOICE_TO_APP_FAILURE = 'SAVE_INVOICE_TO_APP_FAILURE';

// Fetch Invoice By ID
export const FETCH_INVOICE_BY_ID_REQUEST = 'FETCH_INVOICE_BY_ID_REQUEST';
export const FETCH_INVOICE_BY_ID_SUCCESS = 'FETCH_INVOICE_BY_ID_SUCCESS';
export const FETCH_INVOICE_BY_ID_FAILURE = 'FETCH_INVOICE_BY_ID_FAILURE';

// Advanced Features
export const FETCH_INVOICE_ANALYTICS_REQUEST = 'FETCH_INVOICE_ANALYTICS_REQUEST';
export const FETCH_INVOICE_ANALYTICS_SUCCESS = 'FETCH_INVOICE_ANALYTICS_SUCCESS';
export const FETCH_INVOICE_ANALYTICS_FAILURE = 'FETCH_INVOICE_ANALYTICS_FAILURE';

export const BULK_DELETE_INVOICES_REQUEST = 'BULK_DELETE_INVOICES_REQUEST';
export const BULK_DELETE_INVOICES_SUCCESS = 'BULK_DELETE_INVOICES_SUCCESS';
export const BULK_DELETE_INVOICES_FAILURE = 'BULK_DELETE_INVOICES_FAILURE';

export const BULK_UPDATE_INVOICE_STATUS_REQUEST = 'BULK_UPDATE_INVOICE_STATUS_REQUEST';
export const BULK_UPDATE_INVOICE_STATUS_SUCCESS = 'BULK_UPDATE_INVOICE_STATUS_SUCCESS';
export const BULK_UPDATE_INVOICE_STATUS_FAILURE = 'BULK_UPDATE_INVOICE_STATUS_FAILURE';

export const DUPLICATE_INVOICE_REQUEST = 'DUPLICATE_INVOICE_REQUEST';
export const DUPLICATE_INVOICE_SUCCESS = 'DUPLICATE_INVOICE_SUCCESS';
export const DUPLICATE_INVOICE_FAILURE = 'DUPLICATE_INVOICE_FAILURE';

export const SEND_INVOICE_EMAIL_REQUEST = 'SEND_INVOICE_EMAIL_REQUEST';
export const SEND_INVOICE_EMAIL_SUCCESS = 'SEND_INVOICE_EMAIL_SUCCESS';
export const SEND_INVOICE_EMAIL_FAILURE = 'SEND_INVOICE_EMAIL_FAILURE';

export const EXPORT_INVOICES_REQUEST = 'EXPORT_INVOICES_REQUEST';
export const EXPORT_INVOICES_SUCCESS = 'EXPORT_INVOICES_SUCCESS';
export const EXPORT_INVOICES_FAILURE = 'EXPORT_INVOICES_FAILURE';

// Filter and Search
export const SET_INVOICE_FILTERS = 'SET_INVOICE_FILTERS';
export const CLEAR_INVOICE_FILTERS = 'CLEAR_INVOICE_FILTERS';
export const SET_INVOICE_SEARCH = 'SET_INVOICE_SEARCH';

// UI State
export const SET_SELECTED_INVOICES = 'SET_SELECTED_INVOICES';
export const TOGGLE_INVOICE_SELECTION = 'TOGGLE_INVOICE_SELECTION';
export const SELECT_ALL_INVOICES = 'SELECT_ALL_INVOICES';
export const CLEAR_INVOICE_SELECTION = 'CLEAR_INVOICE_SELECTION';

// Analytics View State
export const SET_INVOICE_ANALYTICS_VIEW = 'SET_INVOICE_ANALYTICS_VIEW';
export const CLEAR_INVOICE_ANALYTICS_VIEW = 'CLEAR_INVOICE_ANALYTICS_VIEW';
