

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const FETCH_SESSIONS_REQUEST = 'FETCH_SESSIONS_REQUEST';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE';
export const FETCH_SESSION_MESSAGES_REQUEST = 'FETCH_SESSION_MESSAGES_REQUEST';
export const FETCH_SESSION_MESSAGES_SUCCESS = 'FETCH_SESSION_MESSAGES_SUCCESS';
export const FETCH_SESSION_MESSAGES_FAILURE = 'FETCH_SESSION_MESSAGES_FAILURE';
export const START_NEW_CHAT = 'START_NEW_CHAT';