// Client Documents Action Types

// Fetch client documents
export const FETCH_CLIENT_DOCUMENTS_REQUEST = 'FETCH_CLIENT_DOCUMENTS_REQUEST';
export const FETCH_CLIENT_DOCUMENTS_SUCCESS = 'FETCH_CLIENT_DOCUMENTS_SUCCESS';
export const FETCH_CLIENT_DOCUMENTS_FAILURE = 'FETCH_CLIENT_DOCUMENTS_FAILURE';

// Upload document
export const UPLOAD_CLIENT_DOCUMENT_REQUEST = 'UPLOAD_CLIENT_DOCUMENT_REQUEST';
export const UPLOAD_CLIENT_DOCUMENT_SUCCESS = 'UPLOAD_CLIENT_DOCUMENT_SUCCESS';
export const UPLOAD_CLIENT_DOCUMENT_FAILURE = 'UPLOAD_CLIENT_DOCUMENT_FAILURE';
export const UPLOAD_CLIENT_DOCUMENT_PROGRESS = 'UPLOAD_CLIENT_DOCUMENT_PROGRESS';

// Download document
export const DOWNLOAD_CLIENT_DOCUMENT_REQUEST = 'DOWNLOAD_CLIENT_DOCUMENT_REQUEST';
export const DOWNLOAD_CLIENT_DOCUMENT_SUCCESS = 'DOWNLOAD_CLIENT_DOCUMENT_SUCCESS';
export const DOWNLOAD_CLIENT_DOCUMENT_FAILURE = 'DOWNLOAD_CLIENT_DOCUMENT_FAILURE';

// View document
export const VIEW_CLIENT_DOCUMENT_REQUEST = 'VIEW_CLIENT_DOCUMENT_REQUEST';
export const VIEW_CLIENT_DOCUMENT_SUCCESS = 'VIEW_CLIENT_DOCUMENT_SUCCESS';
export const VIEW_CLIENT_DOCUMENT_FAILURE = 'VIEW_CLIENT_DOCUMENT_FAILURE';

// Sign document
export const SIGN_CLIENT_DOCUMENT_REQUEST = 'SIGN_CLIENT_DOCUMENT_REQUEST';
export const SIGN_CLIENT_DOCUMENT_SUCCESS = 'SIGN_CLIENT_DOCUMENT_SUCCESS';
export const SIGN_CLIENT_DOCUMENT_FAILURE = 'SIGN_CLIENT_DOCUMENT_FAILURE';

// Clear document data
export const CLEAR_CLIENT_DOCUMENT_DATA = 'CLEAR_CLIENT_DOCUMENT_DATA';

// Vault (Document Category) Actions
export const FETCH_CLIENT_VAULTS_REQUEST = 'FETCH_CLIENT_VAULTS_REQUEST';
export const FETCH_CLIENT_VAULTS_SUCCESS = 'FETCH_CLIENT_VAULTS_SUCCESS';
export const FETCH_CLIENT_VAULTS_FAILURE = 'FETCH_CLIENT_VAULTS_FAILURE';

export const CREATE_CLIENT_VAULT_REQUEST = 'CREATE_CLIENT_VAULT_REQUEST';
export const CREATE_CLIENT_VAULT_SUCCESS = 'CREATE_CLIENT_VAULT_SUCCESS';
export const CREATE_CLIENT_VAULT_FAILURE = 'CREATE_CLIENT_VAULT_FAILURE';

export const SELECT_CLIENT_VAULT = 'SELECT_CLIENT_VAULT';
export const CLEAR_SELECTED_CLIENT_VAULT = 'CLEAR_SELECTED_CLIENT_VAULT';
